language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: U5snPuEDNtjbknttrKTHNtQskskk0ZlA1+DyCR2Cc2VyRQyU/KVpPyzgExaerqB5OFHIQXzDk0rzey+CpNBJxlWNODS2sskogYCTp701+B12ZUn+o2d5m3U1dcTNyRZ9NCN9/uuXWDc47/RZtL3vgOntJWtJnHPG1r9SfHUeG4lL/85CDahsmnSUv8bi94nbbch/qD3ouoxBqtOd+e20Lau7M5WCcgQmKutLnNXfL/H/6yyZHZXwPdId/rQeAz+ViZ6KvrHr630YhaFt7EFnzOepTRAnZJrJU5oP07YnfUuqDQrrgzC09vABQZca19GEr+n9gEsYmTBMPo1EEaWaApD9ft+AvpWjQz2yPuvY5cXFLYO96//gwrHYLWJK/TNAmJUnNRnI+7L7CT9w+6lysO+e2CdFczo75XO1n7HjUa9KZHs2pYPwsQCci4r66KdZ51CfTX7eW2bNuBQErU9c9bLakZDCFrYRH1UNPGstwsudbDGVcPLX5HDvvU18/ljXEhPd7axMAVkh4/b5x3Eeok+152iCM9MMuAJIx93WxWMDtb5S1FTANitjRaeYy28OC0Rgpxh3BqhFWwp1xf4tTeBc9FB5LoJ+QNEcaCTWzAvz8tbiIF50pdtWWLx4q2OYsezW8x7qIn0IkfPJudENci9t5V1C2AUry+85lP9Yf40=
  file:
    - 'zwitch.js'
    - 'zwitch.min.js'
  on:
    tags: true
